app:
  image: node:8
  container_name: "sxapi-core-dev"
  mem_limit: 1g
  memswap_limit: 2g
  privileged: true
  ports:
    - "8080:8080"
  links:
    - "db-redis"
  environment:
  - NODE_ENV=development
  - APP_PATH=/usr/src/app
  - DATA_PATH=/data
  - CONF_PATH=/conf
  volumes:
  - "./:/usr/src/app:Z"
  - "./sxapi-dev.json:/conf/sxapi.json:Z"
  working_dir: /usr/src/app
  entrypoint: /usr/src/app/run.sh
  
db-redis:
  image: redis:3.2.11-alpine
  container_name: "sxapi-core-dev-redis"
  mem_limit: 1g
  memswap_limit: 2g
  ports:
    - "6379:6379"
  
  
