app:
  container_name: "sxapi-core-dev"
  image: node:8
  environment:
  - SX_DEBUG=true
  - NODE_ENV=development
  - APP_PATH=/usr/src/app
  - DATA_PATH=/data
  - CONF_PATH=/conf
  ports:
    - "8080:8080"
  volumes:
  - "./:/usr/src/app:z"
  - "./sxapi.yml:/conf/sxapi.yml:z"
  - "./test:/test:z"
  working_dir: /usr/src/app
## build application 
#  command: ["npm" , "run" , "build"]
## run application 
#  command: ["npm" , "start"]
## build and start application for dev environement
#  command: ["npm" , "run", "dev"]
## install application for dev environement
#  command: ["npm",  "run", "dev:install"]
## update application depndencies
#  command: ["npm" , "run" , "dev:update"]
## build application for dev environement
#  command: ["npm" , "run" , "dev:build"]
## start application for dev environement
  command: ["npm" , "run" , "dev:start"]
## run application test
#  command: ["npm" , "test"]
## build application for testing
#  command: ["npm" , "run" , "test:build"]
## start application for testing
#  command: ["npm" , "run" , "test:start"]
## build application for production
#  command: ["npm" , "run" , "prod:build"]
## start application for production
#  command: ["npm" , "run" , "prod:start"]
## build and start application for production
#  command: ["npm" , "run" , "prod"]