sxapi:
  build: ./
  container_name: "dev-sxapi-core"
  cpu_shares: 4096
  cpuset: "0"
  mem_limit: 1g
  memswap_limit: 1g
  privileged: true
  restart: "on-failure:2"
  ports:
    - "8080:19777"
  volumes:
    - "/secure/dev/startx/sxapi-sample/samples/simple/txt:/conf:ro"
    - "/secure/dev/startx/sxapi-core:/app:ro"
    - "/tmp/sxapi-data:/data:rw"
    - "/tmp/sxapi-logs:/logs:rw"