sxapi:
  build: ./
  container_name: "dev-sxapi-core"
  cpu_shares: 4096
  cpuset: "0"
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  ports:
    - "8080:19777"
  volumes:
    - "/tmp/sxapi-logs:/logs"
    - "/tmp/sxapi-conf:/conf"
    - "/tmp/sxapi-data:/data"
  environment:
    SERVICE_NAME: "dev-sxapi-core"