v0.0.6:
  build: .
  container_name: "sxapi-core-v0.0.6"
  privileged: true
  ports:
    - "1977:8080"
  volumes:
    - "/secure/dev/startx/sxapi-sample/samples/full:/conf:ro"
    - "/tmp/sxapi-data:/data:rw"
    - "/tmp/sxapi-logs:/logs:rw"
