app:
  container_name: "sxapi-core-dev"
  extends:
    file: docker-compose.yml
    service: app
  volumes:
  - "./:/usr/src/app:z"
  - "./examples/bot/sxapi.yml:/conf/sxapi.yml:z"
  - "./examples/bot/mylib.js:/usr/src/app/mylib.js:z"
  command: ["npm" , "start"]