app:
  container_name: "sxapi-core-dev"
  image: node:8
  environment:
  - NODE_ENV=development
  - APP_PATH=/usr/src/app
  - DATA_PATH=/data
  - CONF_PATH=/conf
  ports:
    - "8080:8080"
  volumes:
  - "./:/usr/src/app:Z"
  - "./sxapi.json:/conf/sxapi.json:Z"
  working_dir: /usr/src/app
  entrypoint: npm
  command: start