master:
  build: .
  container_name: "sxapi-core-v0.0.5"
  privileged: true
  ports:
    - "8080:19777"
  volumes:
    - "/tmp/sxapi-logs:/logs"
    - "/tmp/sxapi-conf:/conf:ro"
    - "/tmp/sxapi-data:/data"
