master:
  build: .
  container_name: "sxapi-core-master"
  privileged: true
  volumes:
    - "/secure/dev/startx/sxapi-sample/samples/full:/conf:ro"
    - "/tmp/sxapi-data:/data:rw"
    - "/tmp/sxapi-logs:/logs:rw"
