v0.0.9:
  build: .
  container_name: "sxapi-core-v0.0.9"
  mem_limit: 1g
  memswap_limit: 2g
  privileged: true
  ports:
    - "8080:8080"
  environment:
  - NODE_ENV=production
  entrypoint: npm start