dev:
  build: .
  container_name: "sxapi-core-dev"
  privileged: true
  ports:
    - "8080:8080"
  volumes:
    - "/secure/dev/startx/sxapi-sample/samples/full:/conf:ro"
    - "/secure/dev/startx/sxapi-core:/app:ro"
    - "/tmp/sxapi-data:/data:rw"
    - "/tmp/sxapi-logs:/logs:rw"
    
#couchbase:
#  image: couchbase:latest
#  ports:
#    - "8091-8094:8091-8094"
#    - "11210:11210"

#redis:
#  image: redis:latest
#  ports:
#    - "6379:6379"