master:
  build: .
  container_name: "sxapi-core-master"
  privileged: true
  ports:
    - "1977:8080"
  volumes:
    - "/tmp/sxapi-logs:/logs"
    - "/tmp/sxapi-conf:/conf:ro"
    - "/tmp/sxapi-data:/data"
