dev:
  build: .
  container_name: "sxapi-core-dev"
  privileged: true
  ports:
    - "8080:19777"
  volumes:
    - "/secure/dev/startx/sxapi-sample/samples/simple/txt:/conf:ro"
    - "/secure/dev/startx/sxapi-core:/app:ro"
    - "/tmp/sxapi-data:/data:rw"
    - "/tmp/sxapi-logs:/logs:rw"