master:
  image: node:8
  container_name: "sxapi-core-master"
  mem_limit: 1g
  memswap_limit: 2g
  privileged: true
  ports:
    - "8080:8080"
  environment:
  - NODE_ENV=development
  volumes:
  - "./:/usr/src/app:Z"
  working_dir: /usr/src/app
  entrypoint: /usr/src/app/run.sh
