app:
  container_name: "sxapi-core-master"
  extends:
    file: docker-compose.yml
    service: app
  links:
    - "db-redis"
#    - "db-memcache"
    - "db-postgres"
    - "db-mariadb"
    - "db-couchbase"
  volumes:
  - "./full-sxapi.json:/conf/sxapi.json:Z"
  command: start
  
db-redis:
  image: redis:3.2.11-alpine
  container_name: "sxapi-core-master-db-redis"
  mem_limit: 1g
  memswap_limit: 2g
  ports:
    - "6379:6379"

#db-memcache:
#  image: memcache:1.5.3-alpine
#  container_name: "sxapi-core-master-db-memcache"
#  mem_limit: 1g
#  memswap_limit: 2g
#  ports:
#    - "11211:11211"
  
db-postgres:
  image: postgres:10.1-alpine
  container_name: "sxapi-core-master-db-postgres"
  restart: always
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: hguyFtgfR4r9R4r76

db-mariadb:
  image: mariadb:5.5
  container_name: "sxapi-core-master-db-mariadb"
  mem_limit: 2g
  memswap_limit: 3g
  environment:
   - MYSQL_ROOT_PASSWORD=root

#dbadminer:
#  image: adminer
#  container_name: "sxapi-core-master-dbadminer"
#  restart: always
#  ports:
#    - 8081:8080
#  links:
#    - "db-postgres"
#    - "db-mariadb"

db-couchbase:
  image: couchbase
  container_name: "sxapi-core-master-db-couchbase"
  ports:
    - 8091-8094:8091-8094
    - 11210:11210


#dbpma:
#  image: phpmyadmin/phpmyadmin:latest
#  container_name: "sxapi-core-master-dbpma"
#  links:
#    - db-mysql:db
#  environment:
#   - PMA_HOST=db
#   - PMA_USER=root
#   - PMA_PASSWORD=root
#   - PMA_VERBOSE=true
#   - PMA_PORT=3306
#   - PMA_ABSOLUTE_URI=http://localhost:1901
#  ports:
#    - "1901:80"

dbtools:
  image: startx/db-tools:latest
  container_name: "sxapi-core-master-dbtools"
  links:
    - db-mariadb:dbm
    - db-couchbase:dbc
  environment:
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=sxapicore_test
   - MYSQL_DATABASE_USER=sxapicore_test
   - MYSQL_DATABASE_PASSWORD=sxapicore_test
   - MYSQL_DUMP_DIR=/data/mysql
   - COUCHBASE_USER=sxapicore_test
   - COUCHBASE_PASSWORD=sxapicore_test
   - COUCHBASE_BUCKET=sxapicore_test
  volumes:
    - "./test/mock_data/couchbase:/data/couchbase:Z"
    - "./test/mock_data/mysql:/data/mysql:Z"
  command: ["init"] 