apiVersion: v1
kind: Template
labels:
  template: "sxapi-demo-example" 
metadata:
  creationTimestamp: null
  name: "sxapi-demo-example"
  annotations:
    openshift.io/display-name: "SXAPI demo example (Ephemeral)" 
    description: >-
      An example SXAPI application with a simple home page. For more information
      about using this template, including OpenShift considerations, see
      https://github.com/startxfr/sxapi-core/blob/master/README.md.


      WARNING: Any data stored will be lost upon pod destruction. Only use this
      template for testing." 
    template.openshift.io/long-description: >-
      This template defines resources needed to develop a SXAPI application,
      you only have to access the config Map and configure your api
      https://github.com/startxfr/sxapi-core/blob/master/Openshift.md. 
    tags: "quickstart,nodejs,sxapi" 
    iconClass: icon-nodejs 
    template.openshift.io/provider-display-name: "STARTX" 
    template.openshift.io/documentation-url: "https://github.com/startxfr/sxapi-core" 
    template.openshift.io/support-url: "https://github.com/startxfr/sxapi-core/issues/new" 
message: "you can now change your config Map to configure your api" 
parameters:
  - name: APP_NAME
    description: "your application name"
    value: demo
  - name: SXAPI_VERSION
    description: "sxapi version to use"
    value: latest
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-config"
    annotations:
      openshift.io/generated-by: STARTX
  data:
    sxapi.json:  |
        {"name":"test","version":"0.111"}
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
    name: "${APP_NAME}"
  spec:
    tags:
    - annotations:
        openshift.io/generated-by: STARTX
      from:
        kind: DockerImage
        name: "startx/sxapi:${SXAPI_VERSION}"
      name: "${SXAPI_VERSION}"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
    name: "${APP_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: STARTX
        labels:
          app: "${APP_NAME}"
          deploymentconfig: "${APP_NAME}"
      spec:
        containers:
        - image: startx/sxapi@sha256:78fc008ef281f16eaa244e2df0df6b89e91fa24a56124202e7938ffd366b3923
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 4
          name: "${APP_NAME}"
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: "${APP_NAME}-config"
            readOnly: true
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 4
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        volumes:
        - name: "${APP_NAME}-config"
          secret:
            defaultMode: 420
            secretName: "${APP_NAME}-config"
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:${SXAPI_VERSION}"
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- kind: ReplicationController
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: STARTX
    labels:
      app: "${APP_NAME}"
      openshift.io/deployment-config.name: "${APP_NAME}"
    name: "${APP_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APP_NAME}"
      deployment: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: "${APP_NAME}"
          openshift.io/deployment.name: "${APP_NAME}"
          openshift.io/generated-by: STARTX
        creationTimestamp: null
        labels:
          app: "${APP_NAME}"
          deployment: "${APP_NAME}"
          deploymentconfig: "${APP_NAME}"
      spec:
        containers:
        - image: startx/sxapi@sha256:78fc008ef281f16eaa244e2df0df6b89e91fa24a56124202e7938ffd366b3923
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 4
          name: "${APP_NAME}"
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 4
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: "${APP_NAME}-config"
            readOnly: true
          resources: {}
          terminationMessagePath: /dev/termination-log
        volumes:
        - name: "${APP_NAME}-config"
          secret:
            defaultMode: 420
            secretName: "${APP_NAME}-config"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    replicas: 0
- kind: Route
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: "${APP_NAME}"
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: "${APP_NAME}"
      weight: 100
    wildcardPolicy: None
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      openshift.io/generated-by: STARTX
      template.openshift.io/expose-service_ip_port: "{.spec.clusterIP}:{.spec.ports[?(.name==\"web\")].port}"
    creationTimestamp: null
    labels:
      app: "${APP_NAME}"
    name: "${APP_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: "${APP_NAME}"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- kind: Pod
  apiVersion: v1
  metadata:
    creationTimestamp: null
    generateName: "${APP_NAME}-"
    labels:
      app: "${APP_NAME}"
      deployment: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
  spec:
    containers:
    - image: startx/sxapi@sha256:78fc008ef281f16eaa244e2df0df6b89e91fa24a56124202e7938ffd366b3923
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /ping
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 4
      name: "${APP_NAME}"
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /ping
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 4
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: "${APP_NAME}-config"
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-54h97
    nodeName: ip-192-168-0-100.eu-west-1.compute.internal
    restartPolicy: Always
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - name: "${APP_NAME}-config"
      secret:
        defaultMode: 420
        secretName: "${APP_NAME}-config"