#!/bin/sh -e
#
# S2I assemble script for the 'sx-dbtools' image.
# The 'assemble' script builds your application source ready to run.
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

S2IPATH=/tmp/src
cd $APP_PATH

if [[ -d $S2IPATH ]]; then
    echo "copy source code to $APP_PATH"
    cp -R $S2IPATH/* $APP_PATH/
    RET=$?
    if [[ -f $S2IPATH/sxapi.yml ]]; then
      echo "copy config file to $CONF_PATH/sxapi.yml"
      cp -f $S2IPATH/sxapi.yml $CONF_PATH/sxapi.yml
    fi;
    if [[ $RET == 0 ]]; then
      rm -rf $S2IPATH
    fi;
fi;

if [[ "$NODE_ENV" == "development" ]]; then
  echo "install npm module"
  npm install -production
else
  echo "install npm module"
  npm install -production
fi;
echo "clean npm module"
npm dedupe
npm cache verify
npm cache clean --force


cd -
exit 0;