#!/bin/sh -e
#
# S2I assemble script for the 'sx-dbtools' image.
# The 'assemble' script builds your application source ready to run.
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cd $APP_PATH
if [[ -d /tmp/src ]]; then
    cp -R /tmp/src/* $APP_PATH/
    if [[ -f /tmp/src/sxapi.json ]]; then
        cp -f /tmp/src/sxapi.json $CONF_PATH/sxapi.json
    fi;
#    rm -rf /tmp/src
fi;
npm install -production
npm dedupe
npm cache verify
npm cache clean --force
cd -
exit 0;