#!/bin/sh -e
#
# S2I assemble script for the 'sx-dbtools' image.
# The 'assemble' script builds your application source ready to run.
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

S2IPATH=/tmp/src
cd $APP_PATH

if [[ -d $S2IPATH ]]; then
    cp -R $S2IPATH/* $APP_PATH/
    RET=$?
    if [[ -f $S2IPATH/sxapi.yml ]]; then
      cp -f $S2IPATH/sxapi.yml $CONF_PATH/sxapi.yml
    fi;
    if [[ $RET == 0 ]]; then
      rm -rf $S2IPATH
    fi;
fi;

if [[ "$NODE_ENV" == "development" ]]; then
  npm install -production
  npm dedupe
  npm cache verify
  npm cache clean --force
else
  npm install -production
  npm dedupe
  npm cache verify
  npm cache clean --force
fi;


cd -
exit 0;