#!/bin/sh -e
#
# S2I run script
# The 'run' script is the entrypoint of your application
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cd $APP_PATH
exec npm start