#!/bin/sh -e
#
# S2I usage script
# The 'usage' script explay how to use the builder
#
# For more information refer to the documentation:
#  https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

cat <<EOF
SXAPI usage

Usage:
  docker run $SX_ID npm [command]

- General Commands:
  start            start nodejs main application
  version          give the version of the npm environement

EOF
exit 0;