kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxapi-template-build
  annotations:
    openshift.io/display-name: SXAPI micro-service application (Builder)
    description: SXAPI micro-service application builder based on alpine linux
    iconClass: icon-nodejs
    tags: builder,startx,alpine,nodejs,sxapi-0.3.61
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://github.com/startxfr/sxapi-core/blob/testing/index.md
    openshift.io/support-url: https://github.com/startxfr/sxapi-core/issues/new
message: |-
  Your application ${APPLICATION_NAME} will be soon deployed in your project.
  Monitor the build and deployement for application availability

  Application : ${APPLICATION_NAME}
  sxapi       : ${IMAGE_NAME}:${IMAGE_VERSION}
  config      : builded ${APPLICATION_NAME} (yaml)
  Pods        : ${REPLICAS_DATA} (${MEMORY_LIMIT})
  service     : ${APPLICATION_NAME} -> 8077
labels:
  template: sxapi-template-build
  provider: startx
  technology: sxapi
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: sxapi
    annotations:
      openshift.io/display-name: Startx SXAPI framework (S2I)
      openshift.io/generated-by: STARTX
  spec:
    tags:
    - name: 0.3.61
      annotations:
        openshift.io/display-name: S2I Startx SXAPI framework (0.3.61)
        description: Builder for Simple and eXtensible API framework based on alpine
          (0.3.61)
        iconClass: icon-nodejs
        tags: builder,startx,alpine,nodejs,sxapi-0.3.61
        supports: sxapi:0.3.61,nodejs,http
        version: 0.3.61
        sampleRepo: https://github.com/startxfr/sxapi-example.git
      from:
        kind: DockerImage
        name: startx/sxapi:0.3.61
    - name: 0.3.59
      annotations:
        openshift.io/display-name: S2I Startx SXAPI framework (0.3.59)
        description: Builder for Simple and eXtensible API framework based on alpine
          (0.3.59)
        iconClass: icon-nodejs
        tags: builder,startx,alpine,nodejs,sxapi-0.3.59
        supports: sxapi:0.3.59,nodejs,http
        version: 0.3.59
        sampleRepo: https://github.com/startxfr/sxapi-example.git
      from:
        kind: DockerImage
        name: startx/sxapi:0.3.59
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      openshift.io/display-name: Application ${APPLICATION_NAME}
      openshift.io/generated-by: STARTX
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: Application ${APPLICATION_NAME}
        description: Base image for the application ${APPLICATION_NAME}
        iconClass: icon-nodejs
        tags: startx,alpine,nodejs,sxapi-0.3.61,application,${APPLICATION_NAME}
        supports: sxapi:0.3.61,nodejs,http
        version: latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${WEBHOOK_TOKEN}_${APPLICATION_NAME}"
    - type: Generic
      generic:
        secret: "${WEBHOOK_TOKEN}_${APPLICATION_NAME}"
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    runPolicy: SerialLatestOnly
    source:
      type: Git
      git:
        uri: "${SOURCE_GIT}"
        ref: "${SOURCE_BRANCH}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: sxapi:latest
        env:
        - name: SX_VERBOSE
          value: 'true'
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
    resources: {}
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 20
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          provider: startx
          template: sxapi-template-build
          deploymentconfig: "${APPLICATION_NAME}"
        annotations:
          openshift.io/generated-by: STARTX
      spec:
        containers:
        - name: "${APPLICATION_NAME}"
          image: " "
          command:
          - npm
          - start
          env:
          - name: APP_PORT
            value: '8077'
          resources: {}
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8077
              scheme: HTTP
            initialDelaySeconds: 4
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8077
              scheme: HTTP
            initialDelaySeconds: 4
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    ports:
    - name: sxapi-http
      protocol: TCP
      port: 8077
      targetPort: 8077
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
    annotations:
      openshift.io/generated-by: STARTX
  spec:
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: sxapi-http
parameters:
- name: APPLICATION_NAME
  displayName: Application name
  description: The name of the created application
  value: sxapi-build-example
  required: true
- name: SOURCE_GIT
  displayName: Source repository
  description: URL to the source code to use during build process
  value: https://github.com/startxfr/sxapi-example.git
  required: true
- name: SOURCE_BRANCH
  displayName: Source branch
  description: Name of the default branch
  value: master
  required: true
- name: WEBHOOK_TOKEN
  displayName: Webhook token
  description: Secret token to use for webhook to github or generic
  generate: expression
  from: "[a-zA-Z0-9]{24}"
  required: true
