app:
  image: node:12-alpine
  container_name: "sxapi-core-dev"
  ports:
    - "8077:8077"
  environment:
  - NODE_ENV=development
  - APP_PORT=8077
  - APP_PATH=/app
  - DATA_PATH=/data
  - CONF_PATH=/conf
  volumes:
  - "./:/app:z"
  - "./sxapi.yml:/conf/sxapi.yml:z"
  working_dir: /app
  entrypoint: npm
  command: start