app:
  image: node:10-alpine
  container_name: "sxapi-core-dev"
  ports:
    - "8077:8077"
  environment:
  - NODE_ENV=development
  - APP_PATH=/usr/src/app
  - DATA_PATH=/data
  - CONF_PATH=/conf
  volumes:
  - "./:/usr/src/app:z"
  - "./sxapi.yml:/conf/sxapi.yml:z"
  working_dir: /usr/src/app
  entrypoint: npm
  command: start