apiVersion: v1
kind: Template
metadata:
  name: sxapi-configmap-template
  annotations:
    description: Template for creating an SXAPI microservice with configuration stored in a configMap object
    iconClass: icon-nodejs
    tags: sxapi,api,nodejs,startx,microservice
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
  data:
    sxapi.json: "${SXAPI_CONF}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
  spec:
    clusterIP: None
    ports:
    - name: app
      port: 8080
    selector:
      name: "${APPLICATION_NAME}"
      type: application
- kind: StatefulSet
  apiVersion: apps/v1beta1
  metadata:
    name: "${APPLICATION_NAME}"
  spec:
    serviceName: "${APPLICATION_NAME}"
    replicas: "${REPLICAS_DATA}"
    template:
      metadata:
        labels:
          name: "${APPLICATION_NAME}"
          app: sxapi
          type: application
        annotations:
          pod.alpha.kubernetes.io/initialized: 'true'
          scheduler.alpha.kubernetes.io/affinity: "{}"
      spec:
        terminationGracePeriodSeconds: 86400
        containers:
        - name: sxapi-default
          image: "${REGISTRY}:${IMAGE_NAME}"
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
          lifecycle:
            preStop:
              exec:
                command:
                - "npm"
                - stop
          ports:
          - containerPort: 8080
            name: app
          resources:
            requests:
              memory: "${MEMORY_LIMIT}"
              cpu: 0.1
            limits:
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          - mountPath: "/conf"
            name: conf
        volumes:
          - name: conf
            configMap:
              name: "${APPLICATION_NAME}"
              items:
              - key: sxapi.json
                path: sxapi.json
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application.
  value: sxapi-demo
  required: true
- name: IMAGE_NAME
  value: 0.2.3
  required: true
- name: REGISTRY
  value: "startx/sxapi"
  required: true
- name: REPLICAS_DATA
  displayName: Desired Pod count for data nodes
  description: How many data nodes should be provisioned? This value can be changed
    later, by scaling up/down.
  value: '2'
  required: true
- name: MEMORY_LIMIT
  displayName: Memory Limit for data nodes
  description: Maximum amount of memory data container can use.
  value: 128Mi
- name: SXAPI_CONF
  displayName: Configuration object (injected into the configMap)
  description: Json object string describing the application a see in https://github.com/startx/sxapi-core/blob/master/docs/guides/2.Configure.md
  value: "{ \"name\": \"sample-api\",\"description\": \"my desc\", \"version\": \"0.0.0\", \"server\": { \"endpoints\": [ { \"path\": \"/\", \"body\": \"<html><head></head><body><h1>My API</h1></body></html>\" } ] } }"
  required: true
labels:
  template: sxapi-configMap-template