apiVersion: v1
kind: Template
metadata:
  name: sxapi-cm-defined-template
  annotations:
    openshift.io/display-name: SXAPI (defined configmap)
    description: Template for creating an SXAPI microservice where configuration 
      (defined during templating processing) is stored in a configMap object
      for more information see https://hub.docker.com/r/startx/sxapi
    iconClass: icon-nodejs
    tags: sxapi,api,nodejs,startx,microservice
    openshift.io/provider-display-name: STARTX
    openshift.io/documentation-url: https://hub.docker.com/r/startx/sxapi
    openshift.io/support-url: https://github.com/startxfr/sxapi-core/issues/new
labels:
  template: sxapi-cm-defined-template
message: |-
  Your application ${APPLICATION_NAME} will be soon deployed in your project.
  Monitor the deployement for application availability and
  Follow created route to browse your running application

  Application : ${APPLICATION_NAME}
  sxapi       : ${REGISTRY}:${IMAGE_NAME}
  config      : configmap ${APPLICATION_NAME} (json)
  Pods        : ${REPLICAS_DATA} (${MEMORY_LIMIT})
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      openshift.io/display-name: Sxapi configuration ${APPLICATION_NAME}
      openshift.io/generated-by: STARTX
  data:
    sxapi.yml: "${SXAPI_CONF}"
- kind: StatefulSet
  apiVersion: apps/v1beta1
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      openshift.io/display-name: Application ${APPLICATION_NAME}
      openshift.io/generated-by: STARTX
  spec:
    serviceName: "${APPLICATION_NAME}"
    replicas: "${REPLICAS_DATA}"
    template:
      metadata:
        labels:
          name: "${APPLICATION_NAME}"
          app: sxapi
          type: application
        annotations:
          pod.alpha.kubernetes.io/initialized: 'true'
          scheduler.alpha.kubernetes.io/affinity: "{}"
      spec:
        terminationGracePeriodSeconds: 86400
        containers:
        - name: sxapi-default
          image: "${REGISTRY}:${IMAGE_NAME}"
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: 8077
            timeoutSeconds: 2
          lifecycle:
            preStop:
              exec:
                command:
                - "npm"
                - stop
          ports:
          - name: sxapi
            containerPort: 8077
          resources:
            requests:
              memory: "${MEMORY_LIMIT}"
              cpu: 0.1
            limits:
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          - mountPath: "/conf"
            name: conf
        volumes:
          - name: conf
            configMap:
              name: "${APPLICATION_NAME}"
              items:
              - key: sxapi.yml
                path: sxapi.yml
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      openshift.io/display-name: Service ${APPLICATION_NAME}
      openshift.io/generated-by: STARTX
  spec:
    clusterIP: None
    ports:
    - name: sxapi
      port: 8077
    selector:
      name: "${APPLICATION_NAME}"
      type: application
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    annotations:
      openshift.io/display-name: Route ${APPLICATION_NAME}
      openshift.io/generated-by: STARTX
  spec:
    port:
      targetPort: sxapi
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    wildcardPolicy: None
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  description: The name of the application.
  value: sxapi-demo
  required: true
- name: IMAGE_NAME
  value: 0.3.3
  required: true
- name: REGISTRY
  value: "startx/sxapi"
  required: true
- name: REPLICAS_DATA
  displayName: Desired Pod count for data nodes
  description: How many data nodes should be provisioned? This value can be changed
    later, by scaling up/down.
  value: '2'
  required: true
- name: MEMORY_LIMIT
  displayName: Memory Limit for data nodes
  description: Maximum amount of memory data container can use.
  value: 128Mi
- name: SXAPI_CONF
  displayName: Configuration object (injected into the configMap)
  description: Json object string describing the application a see in https://github.com/startx/sxapi-core/blob/master/docs/guides/2.Configure.md
  value: "{ \"name\": \"sample-api\",\"description\": \"my desc\", \"version\": \"0.0.0\", \"server\": { \"endpoints\": [ { \"path\": \"/\", \"body\": \"<html><head></head><body><h1>My API</h1></body></html>\" } ] } }"
  required: true